apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 1m
  path: ./fluxcd/infrastructure/overlays/home-lab
  prune: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
