apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-install
  namespace: flux-system
spec:
  interval: 10m
  path: ./fluxcd/infrastructure/overlays/home-lab/metallb-install
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-configuration
  namespace: flux-system
spec:
  interval: 10m
  path: ./fluxcd/infrastructure/overlays/home-lab/metallb-configuration
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: metallb-install
