---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  interval: 15m # Drift detection interval
  timeout: 5m
  chart:
    spec:
      chart: argocd
      version: v1.19.2
      sourceRef:
        kind: HelmRepository
        name: argocd
        namespace: argocd
      interval: 5m # Chart source interval
  releaseName: argocd
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
  values:
    installCRDs: true # Ensure CRDs are installed
