apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: argocd
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./fluxcd/apps/overlays/home-lab/argocd
  targetNamespace: argocd
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system