---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  type: "oci"
  interval: 5h
  url: oci://quay.io/jetstack/charts/cert-manager