---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: metallb
      version: '0.15.3'
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: metallb-system
      interval: 5h
  releaseName: metallb
  targetNamespace: metallb-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled