apiVersion: infra.essity.com/v1alpha1
kind: TfRun
metadata:
  labels:
    app.kubernetes.io/name: orchestrator-api
    app.kubernetes.io/managed-by: kustomize
  name: tfrun-sample-02
spec:
  # runInterval:
  #   time: 720h
  forProvider:
    credentialsSecretRef: tf-credentials
  engine:
    type: opentofu
    version: "1.10.5"
  source:
    module: https://github.com/vimal-vijayan/my-app.git
    ref: v0.0.4
    credentialsSecretRef: git-credentials
  backend:
    cloud:
      provider: scalr
      hostname: essity.scalr.io
      organization: cet-launchpad
      workspace: demo-workspace-02
      agentPoolId: "ap-v0p08qgiq6mohe7ns"
  arguments:
    autoApprove: "true"
  vars:
    name: "vimal-doing-test"
    object_example:
      - name: "vimal"
        age: 30
      - name: "vijayan"
        age: 25