apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: demo-app
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./fluxcd/apps/home-lab
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system